---
- name: restart promtail
  systemd:
    name: promtail
    state: restarted
    daemon_reload: true
  become: true

- name: reload promtail
  systemd:
    name: promtail
    state: reloaded
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true