---
- name: Create logrotate configuration for promtail
  template:
    src: promtail.logrotate.j2
    dest: /etc/logrotate.d/promtail
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure logrotate service is enabled
  systemd:
    name: logrotate.timer
    enabled: true
    state: started
  become: true
  when: ansible_service_mgr == "systemd"