---
- name: Include system preparation tasks
  include_tasks: system.yml
  tags:
    - ufw
    - system

- name: Include installation tasks
  include_tasks: install.yml
  tags:
    - ufw
    - install

- name: Include configuration tasks
  include_tasks: configure.yml
  tags:
    - ufw
    - configure

- name: Include rules management tasks
  include_tasks: rules.yml
  tags:
    - ufw
    - rules

- name: Include service management tasks
  include_tasks: service.yml
  tags:
    - ufw
    - service

- name: Include validation tasks
  include_tasks: validate.yml
  tags:
    - ufw
    - validate