---
- name: restart fluent-bit
  systemd:
    name: fluent-bit
    state: restarted
    daemon_reload: true
  become: true

- name: reload fluent-bit
  systemd:
    name: fluent-bit
    state: reloaded
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true